title: Miscellaneous Motifs
description: An uncanny notion
remote_theme: UncannyMisc/cayman

collections:
  tutorials:
    remote_theme: UncannyMisc/cayman
    output: true
    permalink: /PlasmaTutorials/:title
    collections_dir: /PlasmaTutorials/tutorials