title: Miscellaneous Motifs
description: An uncanny notion
remote_theme: UncannyMisc/cayman
baseurl: /PlasmaTutorials

collections:
  tutorials:
    remote_theme: UncannyMisc/cayman
    output: true
    permalink: /:categories/:title
    relative_directory: /PlasmaTutorials/tutorials