title: Miscellaneous Motifs
description: An uncanny notion
remote_theme: UncannyMisc/cayman

collections:
  tutorials:
    output: true
    permalink: /:title
    collections_dir: /PlasmaTutorials/tutorials
    remote_theme: UncannyMisc/cayman