title: Miscellaneous Motifs
description: An uncanny notion
remote_theme: UncannyMisc/cayman
baseurl: /PlasmaTutorials
url: https://uncannymisc.github.io/

collections:
  tutorials:
    layout: default
    output: true
    permalink: /:title
    relative_directory: /PlasmaTutorials/tutorials